sudo: required
services:
  - docker

before_install:
  - docker build -t damircosic/extradr -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damircosic/extradr yarn test

after_success:
  - docker build -t damircosic/extradr-client ./client
  - docker build -t damircosic/extradr-nginx ./nginx
  - docker build -t damircosic/extradr-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push damircosic/extradr-client
  - docker push damircosic/extradr-nginx
  - docker push damircosic/extradr-server
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "extradr"
  env: "Extradr-env"
  bucket_name: "elasticbeanstalk-us-east-2-496619540486"
  bucket_path: "extradr"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
